version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY:-django-insecure-dev-key-change-in-production}
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:80
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    networks:
      - expense-tracker-network
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend/expense-tracker-frontend
      dockerfile: Dockerfile
    container_name: expense-tracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    networks:
      - expense-tracker-network
    restart: unless-stopped

networks:
  expense-tracker-network:
    driver: bridge

volumes:
  db_data:
