# Generated by Django 4.2.7 on 2025-09-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#007bff", max_length=7),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("checking", "Checking"),
                    ("savings", "Savings"),
                    ("credit_card", "Credit Card"),
                    ("cash", "Cash"),
                    ("investment", "Investment"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("transfer", "Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
